/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2026 robinpie
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/* Generated by !~ATH to C89 transpiler */
#include "ath_runtime.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

static AthValue _rite_array_set(AthScope*,int,AthValue*);
static AthValue _rite__array_set_loop(AthScope*,int,AthValue*);
static AthValue _rite_record_received(AthScope*,int,AthValue*);
static AthValue _rite_build_ack_ranges(AthScope*,int,AthValue*);
static AthValue _rite__build_ranges(AthScope*,int,AthValue*);
static AthValue _rite_count_newly_acked(AthScope*,int,AthValue*);
static AthValue _rite__count_acked_loop(AthScope*,int,AthValue*);
static AthValue _rite_detect_losses(AthScope*,int,AthValue*);
static AthValue _rite__detect_loss_loop(AthScope*,int,AthValue*);
static AthValue _rite_process_ack(AthScope*,int,AthValue*);
static AthValue _rite_transmit_packet(AthScope*,int,AthValue*);
static AthValue _rite_drain_retransmit_queue(AthScope*,int,AthValue*);
static AthValue _rite_send_burst(AthScope*,int,AthValue*);
static AthValue _rite_sim_cycle(AthScope*,int,AthValue*);
typedef struct _FMain _FMain;
static void _s0__FMain(AthCont*,AthValue);
static AthValue _rite_make_packet(AthScope*,int,AthValue*);
static AthValue _rite_make_ack(AthScope*,int,AthValue*);
static AthValue _rite_is_acked(AthScope*,int,AthValue*);
static AthValue _rite__is_acked_loop(AthScope*,int,AthValue*);
static AthValue _rite_make_retransmit(AthScope*,int,AthValue*);
typedef struct _FMod1 _FMod1;
static void _s2__FMod1(AthCont*,AthValue);
static void _FMod1_done(AthCont*,AthValue);
static void _s3__FMain(AthCont*,AthValue);
static AthValue _rite_is_lost(AthScope*,int,AthValue*);
static AthValue _rite_one_way_delay(AthScope*,int,AthValue*);
typedef struct _FMod4 _FMod4;
static void _s5__FMod4(AthCont*,AthValue);
static void _FMod4_done(AthCont*,AthValue);
static void _s6__FMain(AthCont*,AthValue);
static AthValue _rite__max(AthScope*,int,AthValue*);
static AthValue _rite__abs(AthScope*,int,AthValue*);
static AthValue _rite_init_cc(AthScope*,int,AthValue*);
static AthValue _rite_update_rtt(AthScope*,int,AthValue*);
static AthValue _rite_on_ack(AthScope*,int,AthValue*);
static AthValue _rite_on_loss(AthScope*,int,AthValue*);
static AthValue _rite_can_send(AthScope*,int,AthValue*);
static AthValue _rite_compute_pto(AthScope*,int,AthValue*);
static AthValue _rite_time_loss_threshold(AthScope*,int,AthValue*);
typedef struct _FMod7 _FMod7;
static void _s8__FMod7(AthCont*,AthValue);
static void _FMod7_done(AthCont*,AthValue);
static void _s9__FMain(AthCont*,AthValue);
static AthValue _rite_init_streams(AthScope*,int,AthValue*);
static AthValue _rite__build_streams(AthScope*,int,AthValue*);
static AthValue _rite_next_chunk(AthScope*,int,AthValue*);
static AthValue _rite_pick_stream(AthScope*,int,AthValue*);
typedef struct _FMod10 _FMod10;
static void _s11__FMod10(AthCont*,AthValue);
static void _FMod10_done(AthCont*,AthValue);
static void _s12__FMain(AthCont*,AthValue);

static AthValue _rite_make_packet(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"pkt_num",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"stream_id",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"offset",_argc>2?_argv[2]:ath_void(),0);
    ath_scope_define(_sc,"payload_size",_argc>3?_argv[3]:ath_void(),0);
    ath_scope_define(_sc,"send_time",_argc>4?_argv[4]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_map_val(ath_map_new(0));
_t[1]=ath_str_cstr("data");
_t[2]=ath_str_cstr("type");
_args[0]=_t[0];_args[1]=_t[2];_args[2]=_t[1];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[3]=ath_scope_get(_sc,"pkt_num");
_t[4]=ath_str_cstr("pkt_num");
_args[0]=_t[0];_args[1]=_t[4];_args[2]=_t[3];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[5]=ath_scope_get(_sc,"stream_id");
_t[6]=ath_str_cstr("stream_id");
_args[0]=_t[0];_args[1]=_t[6];_args[2]=_t[5];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[7]=ath_scope_get(_sc,"offset");
_t[8]=ath_str_cstr("offset");
_args[0]=_t[0];_args[1]=_t[8];_args[2]=_t[7];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[9]=ath_scope_get(_sc,"payload_size");
_t[10]=ath_str_cstr("size");
_args[0]=_t[0];_args[1]=_t[10];_args[2]=_t[9];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[11]=ath_scope_get(_sc,"send_time");
_t[12]=ath_str_cstr("send_time");
_args[0]=_t[0];_args[1]=_t[12];_args[2]=_t[11];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[13]=ath_bool(1);
_t[14]=ath_str_cstr("ack_eliciting");
_args[0]=_t[0];_args[1]=_t[14];_args[2]=_t[13];
_t[0]=ath_builtin_SET(_sc,3,_args);
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_make_ack(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"largest_acked",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"ack_ranges",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"ack_delay",_argc>2?_argv[2]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_map_val(ath_map_new(0));
_t[1]=ath_str_cstr("ack");
_t[2]=ath_str_cstr("type");
_args[0]=_t[0];_args[1]=_t[2];_args[2]=_t[1];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[3]=ath_scope_get(_sc,"largest_acked");
_t[4]=ath_str_cstr("largest_acked");
_args[0]=_t[0];_args[1]=_t[4];_args[2]=_t[3];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[5]=ath_scope_get(_sc,"ack_ranges");
_t[6]=ath_str_cstr("ack_ranges");
_args[0]=_t[0];_args[1]=_t[6];_args[2]=_t[5];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[7]=ath_scope_get(_sc,"ack_delay");
_t[8]=ath_str_cstr("ack_delay");
_args[0]=_t[0];_args[1]=_t[8];_args[2]=_t[7];
_t[0]=ath_builtin_SET(_sc,3,_args);
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_is_acked(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"pkt_num",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"ack_ranges",_argc>1?_argv[1]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"pkt_num");
_t[1]=ath_scope_get(_sc,"ack_ranges");
_t[2]=ath_int(0L);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[4]=ath_scope_get(_sc,"_is_acked_loop");
_t[3]=ath_call_sync(_sc,_t[4],3,_args);
        _ret=_t[3]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite__is_acked_loop(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"pkt_num",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"ranges",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"i",_argc>2?_argv[2]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_scope_get(_sc,"ranges");
_args[0]=_t[1];
_t[2]=ath_builtin_LENGTH(_sc,1,_args);
_t[3]=ath_ge(_t[0],_t[2]);
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_bool(0);
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"ranges");
_t[1]=ath_scope_get(_sc,"i");
_t[2]=ath_index(_t[0],_t[1]);
        ath_scope_define(_sc,"range",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"pkt_num");
_t[1]=ath_scope_get(_sc,"range");
_t[2]=ath_int(0L);
_t[3]=ath_index(_t[1],_t[2]);
_t[4]=ath_ge(_t[0],_t[3]);
if(ath_is_truthy(_t[4])){_t[5]=ath_scope_get(_sc,"pkt_num");
_t[6]=ath_scope_get(_sc,"range");
_t[7]=ath_int(1L);
_t[8]=ath_index(_t[6],_t[7]);
_t[9]=ath_le(_t[5],_t[8]);
_t[10]=ath_bool(ath_is_truthy(_t[9]));}else{_t[10]=ath_bool(0);}
        if (ath_is_truthy(_t[10])) {
            {
            _t[0]=ath_bool(1);
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"pkt_num");
_t[1]=ath_scope_get(_sc,"ranges");
_t[2]=ath_scope_get(_sc,"i");
_t[3]=ath_int(1L);
_t[4]=ath_add(_t[2],_t[3]);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[4];
_t[6]=ath_scope_get(_sc,"_is_acked_loop");
_t[5]=ath_call_sync(_sc,_t[6],3,_args);
        _ret=_t[5]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_make_retransmit(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"old_pkt",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"new_pkt_num",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"send_time",_argc>2?_argv[2]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_map_val(ath_map_new(0));
_t[1]=ath_str_cstr("data");
_t[2]=ath_str_cstr("type");
_args[0]=_t[0];_args[1]=_t[2];_args[2]=_t[1];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[3]=ath_scope_get(_sc,"new_pkt_num");
_t[4]=ath_str_cstr("pkt_num");
_args[0]=_t[0];_args[1]=_t[4];_args[2]=_t[3];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[5]=ath_scope_get(_sc,"old_pkt");
_t[6]=ath_member(_t[5],"stream_id");
_t[7]=ath_str_cstr("stream_id");
_args[0]=_t[0];_args[1]=_t[7];_args[2]=_t[6];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[8]=ath_scope_get(_sc,"old_pkt");
_t[9]=ath_member(_t[8],"offset");
_t[10]=ath_str_cstr("offset");
_args[0]=_t[0];_args[1]=_t[10];_args[2]=_t[9];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[11]=ath_scope_get(_sc,"old_pkt");
_t[12]=ath_member(_t[11],"size");
_t[13]=ath_str_cstr("size");
_args[0]=_t[0];_args[1]=_t[13];_args[2]=_t[12];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[14]=ath_scope_get(_sc,"send_time");
_t[15]=ath_str_cstr("send_time");
_args[0]=_t[0];_args[1]=_t[15];_args[2]=_t[14];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[16]=ath_bool(1);
_t[17]=ath_str_cstr("ack_eliciting");
_args[0]=_t[0];_args[1]=_t[17];_args[2]=_t[16];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[18]=ath_bool(1);
_t[19]=ath_str_cstr("is_retransmit");
_args[0]=_t[0];_args[1]=_t[19];_args[2]=_t[18];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[20]=ath_scope_get(_sc,"old_pkt");
_t[21]=ath_member(_t[20],"pkt_num");
_t[22]=ath_str_cstr("original_pkt_num");
_args[0]=_t[0];_args[1]=_t[22];_args[2]=_t[21];
_t[0]=ath_builtin_SET(_sc,3,_args);
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

struct _FMod1 { AthCont base; AthScope *scope; AthScope *parent_scope; };
static _FMod1* _FMod1_new(AthCont *next,AthScope *par) {
    _FMod1 *f=(_FMod1*)malloc(sizeof(_FMod1));
    f->base.resume=_s2__FMod1; f->base.next=next; f->base.refcount=1;
    f->scope=ath_scope_new(NULL); f->parent_scope=par;
    ath_scope_define_builtins(f->scope);
    { AthEntity *_mt=ath_entity_this_new();
      ath_scope_define(f->scope,"THIS",ath_entity_val(_mt),0); }
    return f; }
static void _FMod1_free(_FMod1 *f){ath_scope_decref(f->scope);free(f);}
static void _FMod1_done(AthCont *_self, AthValue _unused) {
    _FMod1 *f=(_FMod1*)_self;
    AthMap *_exp=ath_map_new(8);
    ath_map_set(_exp,"make_packet",ath_scope_get(f->scope,"make_packet"));
    ath_map_set(_exp,"make_ack",ath_scope_get(f->scope,"make_ack"));
    ath_map_set(_exp,"is_acked",ath_scope_get(f->scope,"is_acked"));
    ath_map_set(_exp,"_is_acked_loop",ath_scope_get(f->scope,"_is_acked_loop"));
    ath_map_set(_exp,"make_retransmit",ath_scope_get(f->scope,"make_retransmit"));
    ath_scope_define(f->parent_scope,"Pkt",ath_module_val(_exp),0);
    if(f->base.next)ath_eventloop_schedule(f->base.next,ath_void());
    _FMod1_free(f);
}

static void _s2__FMod1(AthCont *_self, AthValue _result) {
    _FMod1 *f=(_FMod1*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    ath_scope_define(f->scope,"make_packet",ath_rite_val(ath_rite_new_sync(f->scope,_rite_make_packet,5)),0);

    ath_scope_define(f->scope,"make_ack",ath_rite_val(ath_rite_new_sync(f->scope,_rite_make_ack,3)),0);

    ath_scope_define(f->scope,"is_acked",ath_rite_val(ath_rite_new_sync(f->scope,_rite_is_acked,2)),0);

    ath_scope_define(f->scope,"_is_acked_loop",ath_rite_val(ath_rite_new_sync(f->scope,_rite__is_acked_loop,3)),0);

    ath_scope_define(f->scope,"make_retransmit",ath_rite_val(ath_rite_new_sync(f->scope,_rite_make_retransmit,3)),0);

    ath_entity_die(ath_scope_get(f->scope,"THIS").as.entity);

    _FMod1_done((AthCont*)f,ath_void());
}
static AthValue _rite_is_lost(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    _ret = ath_void();
        {
        _t[0]=ath_builtin_RANDOM(_sc,0,_args);
        ath_scope_define(_sc,"roll",_t[0],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"roll");
_t[1]=ath_scope_get(_sc,"LOSS_RATE");
_t[2]=ath_lt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_bool(1);
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_bool(0);
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_one_way_delay(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    _ret = ath_void();
        {
        _t[0]=ath_int(0L);
_t[1]=ath_scope_get(_sc,"JITTER");
_t[2]=ath_sub(_t[0],_t[1]);
_t[3]=ath_scope_get(_sc,"JITTER");
_args[0]=_t[2];
_args[1]=_t[3];
_t[4]=ath_builtin_RANDOM_INT(_sc,2,_args);
        ath_scope_define(_sc,"j",_t[4],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"BASE_RTT");
_t[1]=ath_scope_get(_sc,"j");
_t[2]=ath_add(_t[0],_t[1]);
        ath_scope_define(_sc,"result",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"result");
_t[1]=ath_int(1L);
_t[2]=ath_lt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_int(1L);
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"result");
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

struct _FMod4 { AthCont base; AthScope *scope; AthScope *parent_scope; };
static _FMod4* _FMod4_new(AthCont *next,AthScope *par) {
    _FMod4 *f=(_FMod4*)malloc(sizeof(_FMod4));
    f->base.resume=_s5__FMod4; f->base.next=next; f->base.refcount=1;
    f->scope=ath_scope_new(NULL); f->parent_scope=par;
    ath_scope_define_builtins(f->scope);
    { AthEntity *_mt=ath_entity_this_new();
      ath_scope_define(f->scope,"THIS",ath_entity_val(_mt),0); }
    return f; }
static void _FMod4_free(_FMod4 *f){ath_scope_decref(f->scope);free(f);}
static void _FMod4_done(AthCont *_self, AthValue _unused) {
    _FMod4 *f=(_FMod4*)_self;
    AthMap *_exp=ath_map_new(8);
    ath_map_set(_exp,"BASE_RTT",ath_scope_get(f->scope,"BASE_RTT"));
    ath_map_set(_exp,"JITTER",ath_scope_get(f->scope,"JITTER"));
    ath_map_set(_exp,"LOSS_RATE",ath_scope_get(f->scope,"LOSS_RATE"));
    ath_map_set(_exp,"is_lost",ath_scope_get(f->scope,"is_lost"));
    ath_map_set(_exp,"one_way_delay",ath_scope_get(f->scope,"one_way_delay"));
    ath_scope_define(f->parent_scope,"Net",ath_module_val(_exp),0);
    if(f->base.next)ath_eventloop_schedule(f->base.next,ath_void());
    _FMod4_free(f);
}

static void _s5__FMod4(AthCont *_self, AthValue _result) {
    _FMod4 *f=(_FMod4*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    {
    _t[0]=ath_int(50L);
    ath_scope_define(f->scope,"BASE_RTT",_t[0],1);
    }

    {
    _t[1]=ath_int(10L);
    ath_scope_define(f->scope,"JITTER",_t[1],1);
    }

    {
    _t[2]=ath_float(0.02);
    ath_scope_define(f->scope,"LOSS_RATE",_t[2],1);
    }

    ath_scope_define(f->scope,"is_lost",ath_rite_val(ath_rite_new_sync(f->scope,_rite_is_lost,0)),0);

    ath_scope_define(f->scope,"one_way_delay",ath_rite_val(ath_rite_new_sync(f->scope,_rite_one_way_delay,0)),0);

    ath_entity_die(ath_scope_get(f->scope,"THIS").as.entity);

    _FMod4_done((AthCont*)f,ath_void());
}
static AthValue _rite__max(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"a",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"b",_argc>1?_argv[1]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"a");
_t[1]=ath_scope_get(_sc,"b");
_t[2]=ath_gt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"a");
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"b");
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite__abs(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"x",_argc>0?_argv[0]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"x");
_t[1]=ath_int(0L);
_t[2]=ath_lt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_int(0L);
_t[1]=ath_scope_get(_sc,"x");
_t[2]=ath_sub(_t[0],_t[1]);
            _ret=_t[2]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"x");
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_init_cc(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    _ret = ath_void();
        {
        _t[0]=ath_map_val(ath_map_new(0));
_t[1]=ath_scope_get(_sc,"INITIAL_CWND");
_t[2]=ath_str_cstr("cwnd");
_args[0]=_t[0];_args[1]=_t[2];_args[2]=_t[1];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[3]=ath_scope_get(_sc,"SSTHRESH_INITIAL");
_t[4]=ath_str_cstr("ssthresh");
_args[0]=_t[0];_args[1]=_t[4];_args[2]=_t[3];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[5]=ath_int(0L);
_t[6]=ath_str_cstr("bytes_in_flight");
_args[0]=_t[0];_args[1]=_t[6];_args[2]=_t[5];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[7]=ath_scope_get(_sc,"INITIAL_RTT");
_t[8]=ath_str_cstr("smoothed_rtt");
_args[0]=_t[0];_args[1]=_t[8];_args[2]=_t[7];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[9]=ath_scope_get(_sc,"INITIAL_RTT");
_t[10]=ath_int(2L);
_t[11]=ath_div(_t[9],_t[10]);
_t[12]=ath_str_cstr("rttvar");
_args[0]=_t[0];_args[1]=_t[12];_args[2]=_t[11];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[13]=ath_scope_get(_sc,"INITIAL_RTT");
_t[14]=ath_str_cstr("min_rtt");
_args[0]=_t[0];_args[1]=_t[14];_args[2]=_t[13];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[15]=ath_int(0L);
_t[16]=ath_str_cstr("recovery_start");
_args[0]=_t[0];_args[1]=_t[16];_args[2]=_t[15];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[17]=ath_bool(0);
_t[18]=ath_str_cstr("in_recovery");
_args[0]=_t[0];_args[1]=_t[18];_args[2]=_t[17];
_t[0]=ath_builtin_SET(_sc,3,_args);
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_update_rtt(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"cc",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"latest_rtt",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"ack_delay",_argc>2?_argv[2]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"latest_rtt");
        ath_scope_define(_sc,"new_min",_t[0],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"min_rtt");
_t[2]=ath_scope_get(_sc,"latest_rtt");
_t[3]=ath_lt(_t[1],_t[2]);
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"min_rtt");
            ath_scope_set(_sc,"new_min",_t[1]);
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"latest_rtt");
        ath_scope_define(_sc,"adjusted",_t[0],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"latest_rtt");
_t[1]=ath_scope_get(_sc,"new_min");
_t[2]=ath_scope_get(_sc,"ack_delay");
_t[3]=ath_add(_t[1],_t[2]);
_t[4]=ath_gt(_t[0],_t[3]);
        if (ath_is_truthy(_t[4])) {
            {
            _t[0]=ath_scope_get(_sc,"latest_rtt");
_t[1]=ath_scope_get(_sc,"ack_delay");
_t[2]=ath_sub(_t[0],_t[1]);
            ath_scope_set(_sc,"adjusted",_t[2]);
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"rttvar");
        ath_scope_define(_sc,"new_rttvar",_t[1],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"smoothed_rtt");
        ath_scope_define(_sc,"new_srtt",_t[1],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"smoothed_rtt");
_t[2]=ath_scope_get(_sc,"INITIAL_RTT");
_t[3]=ath_eq(_t[1],_t[2]);
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_scope_get(_sc,"latest_rtt");
            ath_scope_set(_sc,"new_srtt",_t[0]);
            }
            {
            _t[0]=ath_scope_get(_sc,"latest_rtt");
_t[1]=ath_int(2L);
_t[2]=ath_div(_t[0],_t[1]);
            ath_scope_set(_sc,"new_rttvar",_t[2]);
            }
        } else {
            {
            _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"smoothed_rtt");
_t[2]=ath_scope_get(_sc,"adjusted");
_t[3]=ath_sub(_t[1],_t[2]);
_args[0]=_t[3];
_t[5]=ath_scope_get(_sc,"_abs");
_t[4]=ath_call_sync(_sc,_t[5],1,_args);
            ath_scope_define(_sc,"diff",_t[4],0);
            }
            {
            _t[0]=ath_int(3L);
_t[1]=ath_scope_get(_sc,"cc");
_t[2]=ath_member(_t[1],"rttvar");
_t[3]=ath_mul(_t[0],_t[2]);
_t[4]=ath_scope_get(_sc,"diff");
_t[5]=ath_add(_t[3],_t[4]);
_args[0]=_t[5];
_t[6]=ath_builtin_FLOAT(_sc,1,_args);
_t[7]=ath_float(4.0);
_t[8]=ath_div(_t[6],_t[7]);
_args[0]=_t[8];
_t[9]=ath_builtin_INT(_sc,1,_args);
            ath_scope_set(_sc,"new_rttvar",_t[9]);
            }
            {
            _t[0]=ath_int(7L);
_t[1]=ath_scope_get(_sc,"cc");
_t[2]=ath_member(_t[1],"smoothed_rtt");
_t[3]=ath_mul(_t[0],_t[2]);
_t[4]=ath_scope_get(_sc,"adjusted");
_t[5]=ath_add(_t[3],_t[4]);
_args[0]=_t[5];
_t[6]=ath_builtin_FLOAT(_sc,1,_args);
_t[7]=ath_float(8.0);
_t[8]=ath_div(_t[6],_t[7]);
_args[0]=_t[8];
_t[9]=ath_builtin_INT(_sc,1,_args);
            ath_scope_set(_sc,"new_srtt",_t[9]);
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_str_cstr("smoothed_rtt");
_t[2]=ath_scope_get(_sc,"new_srtt");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[3]=ath_builtin_SET(_sc,3,_args);
_t[4]=ath_str_cstr("rttvar");
_t[5]=ath_scope_get(_sc,"new_rttvar");
_args[0]=_t[3];
_args[1]=_t[4];
_args[2]=_t[5];
_t[6]=ath_builtin_SET(_sc,3,_args);
_t[7]=ath_str_cstr("min_rtt");
_t[8]=ath_scope_get(_sc,"new_min");
_args[0]=_t[6];
_args[1]=_t[7];
_args[2]=_t[8];
_t[9]=ath_builtin_SET(_sc,3,_args);
        _ret=_t[9]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_on_ack(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"cc",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"acked_bytes",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"now",_argc>2?_argv[2]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"in_recovery");
if(ath_is_truthy(_t[1])){_t[2]=ath_scope_get(_sc,"now");
_t[3]=ath_scope_get(_sc,"cc");
_t[4]=ath_member(_t[3],"recovery_start");
_t[5]=ath_scope_get(_sc,"cc");
_t[6]=ath_member(_t[5],"smoothed_rtt");
_t[7]=ath_add(_t[4],_t[6]);
_t[8]=ath_lt(_t[2],_t[7]);
_t[9]=ath_bool(ath_is_truthy(_t[8]));}else{_t[9]=ath_bool(0);}
        if (ath_is_truthy(_t[9])) {
            {
            _t[0]=ath_int(0L);
_t[1]=ath_scope_get(_sc,"cc");
_t[2]=ath_member(_t[1],"bytes_in_flight");
_t[3]=ath_scope_get(_sc,"acked_bytes");
_t[4]=ath_sub(_t[2],_t[3]);
_args[0]=_t[0];
_args[1]=_t[4];
_t[6]=ath_scope_get(_sc,"_max");
_t[5]=ath_call_sync(_sc,_t[6],2,_args);
            ath_scope_define(_sc,"new_bif",_t[5],0);
            }
            {
            _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_str_cstr("bytes_in_flight");
_t[2]=ath_scope_get(_sc,"new_bif");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[3]=ath_builtin_SET(_sc,3,_args);
            _ret=_t[3]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"cwnd");
        ath_scope_define(_sc,"new_cwnd",_t[1],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"cwnd");
_t[2]=ath_scope_get(_sc,"cc");
_t[3]=ath_member(_t[2],"ssthresh");
_t[4]=ath_lt(_t[1],_t[3]);
        if (ath_is_truthy(_t[4])) {
            {
            _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"cwnd");
_t[2]=ath_scope_get(_sc,"acked_bytes");
_t[3]=ath_add(_t[1],_t[2]);
            ath_scope_set(_sc,"new_cwnd",_t[3]);
            }
        } else {
            {
            _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"cwnd");
_t[2]=ath_scope_get(_sc,"MAX_DATAGRAM_SIZE");
_t[3]=ath_scope_get(_sc,"acked_bytes");
_t[4]=ath_mul(_t[2],_t[3]);
_args[0]=_t[4];
_t[5]=ath_builtin_FLOAT(_sc,1,_args);
_t[6]=ath_scope_get(_sc,"cc");
_t[7]=ath_member(_t[6],"cwnd");
_args[0]=_t[7];
_t[8]=ath_builtin_FLOAT(_sc,1,_args);
_t[9]=ath_div(_t[5],_t[8]);
_args[0]=_t[9];
_t[10]=ath_builtin_INT(_sc,1,_args);
_t[11]=ath_add(_t[1],_t[10]);
            ath_scope_set(_sc,"new_cwnd",_t[11]);
            }
        }
        }
        {
        _t[0]=ath_int(0L);
_t[1]=ath_scope_get(_sc,"cc");
_t[2]=ath_member(_t[1],"bytes_in_flight");
_t[3]=ath_scope_get(_sc,"acked_bytes");
_t[4]=ath_sub(_t[2],_t[3]);
_args[0]=_t[0];
_args[1]=_t[4];
_t[6]=ath_scope_get(_sc,"_max");
_t[5]=ath_call_sync(_sc,_t[6],2,_args);
        ath_scope_define(_sc,"new_bif",_t[5],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_str_cstr("cwnd");
_t[2]=ath_scope_get(_sc,"new_cwnd");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[3]=ath_builtin_SET(_sc,3,_args);
_t[4]=ath_str_cstr("bytes_in_flight");
_t[5]=ath_scope_get(_sc,"new_bif");
_args[0]=_t[3];
_args[1]=_t[4];
_args[2]=_t[5];
_t[6]=ath_builtin_SET(_sc,3,_args);
_t[7]=ath_str_cstr("in_recovery");
_t[8]=ath_bool(0);
_args[0]=_t[6];
_args[1]=_t[7];
_args[2]=_t[8];
_t[9]=ath_builtin_SET(_sc,3,_args);
        _ret=_t[9]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_on_loss(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"cc",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"lost_bytes",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"now",_argc>2?_argv[2]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"in_recovery");
        if (ath_is_truthy(_t[1])) {
            {
            _t[0]=ath_scope_get(_sc,"cc");
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"cwnd");
_t[2]=ath_int(2L);
_t[3]=ath_div(_t[1],_t[2]);
_t[4]=ath_scope_get(_sc,"MIN_CWND");
_args[0]=_t[3];
_args[1]=_t[4];
_t[6]=ath_scope_get(_sc,"_max");
_t[5]=ath_call_sync(_sc,_t[6],2,_args);
        ath_scope_define(_sc,"new_ssthresh",_t[5],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_str_cstr("ssthresh");
_t[2]=ath_scope_get(_sc,"new_ssthresh");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[3]=ath_builtin_SET(_sc,3,_args);
_t[4]=ath_str_cstr("cwnd");
_t[5]=ath_scope_get(_sc,"new_ssthresh");
_args[0]=_t[3];
_args[1]=_t[4];
_args[2]=_t[5];
_t[6]=ath_builtin_SET(_sc,3,_args);
_t[7]=ath_str_cstr("in_recovery");
_t[8]=ath_bool(1);
_args[0]=_t[6];
_args[1]=_t[7];
_args[2]=_t[8];
_t[9]=ath_builtin_SET(_sc,3,_args);
_t[10]=ath_str_cstr("recovery_start");
_t[11]=ath_scope_get(_sc,"now");
_args[0]=_t[9];
_args[1]=_t[10];
_args[2]=_t[11];
_t[12]=ath_builtin_SET(_sc,3,_args);
_t[13]=ath_str_cstr("bytes_in_flight");
_t[14]=ath_int(0L);
_t[15]=ath_scope_get(_sc,"cc");
_t[16]=ath_member(_t[15],"bytes_in_flight");
_t[17]=ath_scope_get(_sc,"lost_bytes");
_t[18]=ath_sub(_t[16],_t[17]);
_args[0]=_t[14];
_args[1]=_t[18];
_t[20]=ath_scope_get(_sc,"_max");
_t[19]=ath_call_sync(_sc,_t[20],2,_args);
_args[0]=_t[12];
_args[1]=_t[13];
_args[2]=_t[19];
_t[21]=ath_builtin_SET(_sc,3,_args);
        _ret=_t[21]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_can_send(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"cc",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"packet_size",_argc>1?_argv[1]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"bytes_in_flight");
_t[2]=ath_scope_get(_sc,"packet_size");
_t[3]=ath_add(_t[1],_t[2]);
_t[4]=ath_scope_get(_sc,"cc");
_t[5]=ath_member(_t[4],"cwnd");
_t[6]=ath_le(_t[3],_t[5]);
        _ret=_t[6]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_compute_pto(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"cc",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"max_ack_delay",_argc>1?_argv[1]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"smoothed_rtt");
_t[2]=ath_int(4L);
_t[3]=ath_scope_get(_sc,"cc");
_t[4]=ath_member(_t[3],"rttvar");
_t[5]=ath_mul(_t[2],_t[4]);
_t[6]=ath_int(1L);
_args[0]=_t[5];
_args[1]=_t[6];
_t[8]=ath_scope_get(_sc,"_max");
_t[7]=ath_call_sync(_sc,_t[8],2,_args);
_t[9]=ath_add(_t[1],_t[7]);
        ath_scope_define(_sc,"pto_base",_t[9],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"pto_base");
_t[1]=ath_scope_get(_sc,"max_ack_delay");
_t[2]=ath_add(_t[0],_t[1]);
        _ret=_t[2]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_time_loss_threshold(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"cc",_argc>0?_argv[0]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"cc");
_t[1]=ath_member(_t[0],"smoothed_rtt");
_t[2]=ath_scope_get(_sc,"cc");
_t[3]=ath_member(_t[2],"smoothed_rtt");
_t[4]=ath_int(8L);
_t[5]=ath_div(_t[3],_t[4]);
_t[6]=ath_add(_t[1],_t[5]);
        ath_scope_define(_sc,"threshold",_t[6],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"threshold");
_t[1]=ath_int(1L);
_args[0]=_t[0];
_args[1]=_t[1];
_t[3]=ath_scope_get(_sc,"_max");
_t[2]=ath_call_sync(_sc,_t[3],2,_args);
        _ret=_t[2]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

struct _FMod7 { AthCont base; AthScope *scope; AthScope *parent_scope; };
static _FMod7* _FMod7_new(AthCont *next,AthScope *par) {
    _FMod7 *f=(_FMod7*)malloc(sizeof(_FMod7));
    f->base.resume=_s8__FMod7; f->base.next=next; f->base.refcount=1;
    f->scope=ath_scope_new(NULL); f->parent_scope=par;
    ath_scope_define_builtins(f->scope);
    { AthEntity *_mt=ath_entity_this_new();
      ath_scope_define(f->scope,"THIS",ath_entity_val(_mt),0); }
    return f; }
static void _FMod7_free(_FMod7 *f){ath_scope_decref(f->scope);free(f);}
static void _FMod7_done(AthCont *_self, AthValue _unused) {
    _FMod7 *f=(_FMod7*)_self;
    AthMap *_exp=ath_map_new(8);
    ath_map_set(_exp,"INITIAL_RTT",ath_scope_get(f->scope,"INITIAL_RTT"));
    ath_map_set(_exp,"MAX_DATAGRAM_SIZE",ath_scope_get(f->scope,"MAX_DATAGRAM_SIZE"));
    ath_map_set(_exp,"MIN_CWND",ath_scope_get(f->scope,"MIN_CWND"));
    ath_map_set(_exp,"INITIAL_CWND",ath_scope_get(f->scope,"INITIAL_CWND"));
    ath_map_set(_exp,"SSTHRESH_INITIAL",ath_scope_get(f->scope,"SSTHRESH_INITIAL"));
    ath_map_set(_exp,"_max",ath_scope_get(f->scope,"_max"));
    ath_map_set(_exp,"_abs",ath_scope_get(f->scope,"_abs"));
    ath_map_set(_exp,"init_cc",ath_scope_get(f->scope,"init_cc"));
    ath_map_set(_exp,"update_rtt",ath_scope_get(f->scope,"update_rtt"));
    ath_map_set(_exp,"on_ack",ath_scope_get(f->scope,"on_ack"));
    ath_map_set(_exp,"on_loss",ath_scope_get(f->scope,"on_loss"));
    ath_map_set(_exp,"can_send",ath_scope_get(f->scope,"can_send"));
    ath_map_set(_exp,"compute_pto",ath_scope_get(f->scope,"compute_pto"));
    ath_map_set(_exp,"time_loss_threshold",ath_scope_get(f->scope,"time_loss_threshold"));
    ath_scope_define(f->parent_scope,"CC",ath_module_val(_exp),0);
    if(f->base.next)ath_eventloop_schedule(f->base.next,ath_void());
    _FMod7_free(f);
}

static void _s8__FMod7(AthCont *_self, AthValue _result) {
    _FMod7 *f=(_FMod7*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    {
    _t[0]=ath_int(100L);
    ath_scope_define(f->scope,"INITIAL_RTT",_t[0],1);
    }

    {
    _t[1]=ath_int(1200L);
    ath_scope_define(f->scope,"MAX_DATAGRAM_SIZE",_t[1],1);
    }

    {
    _t[2]=ath_int(2400L);
    ath_scope_define(f->scope,"MIN_CWND",_t[2],1);
    }

    {
    _t[3]=ath_int(14720L);
    ath_scope_define(f->scope,"INITIAL_CWND",_t[3],1);
    }

    {
    _t[4]=ath_int(999999L);
    ath_scope_define(f->scope,"SSTHRESH_INITIAL",_t[4],1);
    }

    ath_scope_define(f->scope,"_max",ath_rite_val(ath_rite_new_sync(f->scope,_rite__max,2)),0);

    ath_scope_define(f->scope,"_abs",ath_rite_val(ath_rite_new_sync(f->scope,_rite__abs,1)),0);

    ath_scope_define(f->scope,"init_cc",ath_rite_val(ath_rite_new_sync(f->scope,_rite_init_cc,0)),0);

    ath_scope_define(f->scope,"update_rtt",ath_rite_val(ath_rite_new_sync(f->scope,_rite_update_rtt,3)),0);

    ath_scope_define(f->scope,"on_ack",ath_rite_val(ath_rite_new_sync(f->scope,_rite_on_ack,3)),0);

    ath_scope_define(f->scope,"on_loss",ath_rite_val(ath_rite_new_sync(f->scope,_rite_on_loss,3)),0);

    ath_scope_define(f->scope,"can_send",ath_rite_val(ath_rite_new_sync(f->scope,_rite_can_send,2)),0);

    ath_scope_define(f->scope,"compute_pto",ath_rite_val(ath_rite_new_sync(f->scope,_rite_compute_pto,2)),0);

    ath_scope_define(f->scope,"time_loss_threshold",ath_rite_val(ath_rite_new_sync(f->scope,_rite_time_loss_threshold,1)),0);

    ath_entity_die(ath_scope_get(f->scope,"THIS").as.entity);

    _FMod7_done((AthCont*)f,ath_void());
}
static AthValue _rite_init_streams(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"num_streams",_argc>0?_argv[0]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"num_streams");
_t[1]=ath_int(0L);
_t[2]=ath_array_val(ath_array_new(0));
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[4]=ath_scope_get(_sc,"_build_streams");
_t[3]=ath_call_sync(_sc,_t[4],3,_args);
        _ret=_t[3]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite__build_streams(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"n",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"i",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"acc",_argc>2?_argv[2]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_scope_get(_sc,"n");
_t[2]=ath_ge(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"acc");
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_map_val(ath_map_new(0));
_t[1]=ath_scope_get(_sc,"i");
_t[2]=ath_str_cstr("id");
_args[0]=_t[0];_args[1]=_t[2];_args[2]=_t[1];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[3]=ath_int(0L);
_t[4]=ath_str_cstr("send_offset");
_args[0]=_t[0];_args[1]=_t[4];_args[2]=_t[3];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[5]=ath_int(0L);
_t[6]=ath_str_cstr("recv_offset");
_args[0]=_t[0];_args[1]=_t[6];_args[2]=_t[5];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[7]=ath_map_val(ath_map_new(0));
_t[8]=ath_str_cstr("recv_buffer");
_args[0]=_t[0];_args[1]=_t[8];_args[2]=_t[7];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[9]=ath_int(0L);
_t[10]=ath_str_cstr("total_bytes");
_args[0]=_t[0];_args[1]=_t[10];_args[2]=_t[9];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[11]=ath_bool(0);
_t[12]=ath_str_cstr("finished");
_args[0]=_t[0];_args[1]=_t[12];_args[2]=_t[11];
_t[0]=ath_builtin_SET(_sc,3,_args);
        ath_scope_define(_sc,"stream",_t[0],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"n");
_t[1]=ath_scope_get(_sc,"i");
_t[2]=ath_int(1L);
_t[3]=ath_add(_t[1],_t[2]);
_t[4]=ath_scope_get(_sc,"acc");
_t[5]=ath_scope_get(_sc,"stream");
_args[0]=_t[4];
_args[1]=_t[5];
_t[6]=ath_builtin_APPEND(_sc,2,_args);
_args[0]=_t[0];
_args[1]=_t[3];
_args[2]=_t[6];
_t[8]=ath_scope_get(_sc,"_build_streams");
_t[7]=ath_call_sync(_sc,_t[8],3,_args);
        _ret=_t[7]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_next_chunk(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"stream",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"chunk_size",_argc>1?_argv[1]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_map_val(ath_map_new(0));
_t[1]=ath_scope_get(_sc,"stream");
_t[2]=ath_member(_t[1],"id");
_t[3]=ath_str_cstr("stream_id");
_args[0]=_t[0];_args[1]=_t[3];_args[2]=_t[2];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[4]=ath_scope_get(_sc,"stream");
_t[5]=ath_member(_t[4],"send_offset");
_t[6]=ath_str_cstr("offset");
_args[0]=_t[0];_args[1]=_t[6];_args[2]=_t[5];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[7]=ath_scope_get(_sc,"chunk_size");
_t[8]=ath_str_cstr("size");
_args[0]=_t[0];_args[1]=_t[8];_args[2]=_t[7];
_t[0]=ath_builtin_SET(_sc,3,_args);
_t[9]=ath_scope_get(_sc,"stream");
_t[10]=ath_member(_t[9],"send_offset");
_t[11]=ath_scope_get(_sc,"chunk_size");
_t[12]=ath_add(_t[10],_t[11]);
_t[13]=ath_str_cstr("new_offset");
_args[0]=_t[0];_args[1]=_t[13];_args[2]=_t[12];
_t[0]=ath_builtin_SET(_sc,3,_args);
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_pick_stream(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"streams",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"last_stream_idx",_argc>1?_argv[1]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"last_stream_idx");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
_t[3]=ath_scope_get(_sc,"streams");
_args[0]=_t[3];
_t[4]=ath_builtin_LENGTH(_sc,1,_args);
_t[5]=ath_mod(_t[2],_t[4]);
        ath_scope_define(_sc,"next",_t[5],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"next");
        _ret=_t[0]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

struct _FMod10 { AthCont base; AthScope *scope; AthScope *parent_scope; };
static _FMod10* _FMod10_new(AthCont *next,AthScope *par) {
    _FMod10 *f=(_FMod10*)malloc(sizeof(_FMod10));
    f->base.resume=_s11__FMod10; f->base.next=next; f->base.refcount=1;
    f->scope=ath_scope_new(NULL); f->parent_scope=par;
    ath_scope_define_builtins(f->scope);
    { AthEntity *_mt=ath_entity_this_new();
      ath_scope_define(f->scope,"THIS",ath_entity_val(_mt),0); }
    return f; }
static void _FMod10_free(_FMod10 *f){ath_scope_decref(f->scope);free(f);}
static void _FMod10_done(AthCont *_self, AthValue _unused) {
    _FMod10 *f=(_FMod10*)_self;
    AthMap *_exp=ath_map_new(8);
    ath_map_set(_exp,"init_streams",ath_scope_get(f->scope,"init_streams"));
    ath_map_set(_exp,"_build_streams",ath_scope_get(f->scope,"_build_streams"));
    ath_map_set(_exp,"next_chunk",ath_scope_get(f->scope,"next_chunk"));
    ath_map_set(_exp,"pick_stream",ath_scope_get(f->scope,"pick_stream"));
    ath_scope_define(f->parent_scope,"Streams",ath_module_val(_exp),0);
    if(f->base.next)ath_eventloop_schedule(f->base.next,ath_void());
    _FMod10_free(f);
}

static void _s11__FMod10(AthCont *_self, AthValue _result) {
    _FMod10 *f=(_FMod10*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    ath_scope_define(f->scope,"init_streams",ath_rite_val(ath_rite_new_sync(f->scope,_rite_init_streams,1)),0);

    ath_scope_define(f->scope,"_build_streams",ath_rite_val(ath_rite_new_sync(f->scope,_rite__build_streams,3)),0);

    ath_scope_define(f->scope,"next_chunk",ath_rite_val(ath_rite_new_sync(f->scope,_rite_next_chunk,2)),0);

    ath_scope_define(f->scope,"pick_stream",ath_rite_val(ath_rite_new_sync(f->scope,_rite_pick_stream,2)),0);

    ath_entity_die(ath_scope_get(f->scope,"THIS").as.entity);

    _FMod10_done((AthCont*)f,ath_void());
}

static AthValue _rite_array_set(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"arr",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"idx",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"val",_argc>2?_argv[2]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"arr");
_t[1]=ath_scope_get(_sc,"idx");
_t[2]=ath_scope_get(_sc,"val");
_t[3]=ath_int(0L);
_t[4]=ath_array_val(ath_array_new(0));
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_args[3]=_t[3];
_args[4]=_t[4];
_t[5]=_rite__array_set_loop(_sc,5,_args);
        _ret=_t[5]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite__array_set_loop(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"arr",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"idx",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"val",_argc>2?_argv[2]:ath_void(),0);
    ath_scope_define(_sc,"i",_argc>3?_argv[3]:ath_void(),0);
    ath_scope_define(_sc,"acc",_argc>4?_argv[4]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_scope_get(_sc,"arr");
_args[0]=_t[1];
_t[2]=ath_builtin_LENGTH(_sc,1,_args);
_t[3]=ath_ge(_t[0],_t[2]);
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_scope_get(_sc,"acc");
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_scope_get(_sc,"idx");
_t[2]=ath_eq(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"arr");
_t[1]=ath_scope_get(_sc,"idx");
_t[2]=ath_scope_get(_sc,"val");
_t[3]=ath_scope_get(_sc,"i");
_t[4]=ath_int(1L);
_t[5]=ath_add(_t[3],_t[4]);
_t[6]=ath_scope_get(_sc,"acc");
_t[7]=ath_scope_get(_sc,"val");
_args[0]=_t[6];
_args[1]=_t[7];
_t[8]=ath_builtin_APPEND(_sc,2,_args);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_args[3]=_t[5];
_args[4]=_t[8];
_t[9]=_rite__array_set_loop(_sc,5,_args);
            _ret=_t[9]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"arr");
_t[1]=ath_scope_get(_sc,"idx");
_t[2]=ath_scope_get(_sc,"val");
_t[3]=ath_scope_get(_sc,"i");
_t[4]=ath_int(1L);
_t[5]=ath_add(_t[3],_t[4]);
_t[6]=ath_scope_get(_sc,"acc");
_t[7]=ath_scope_get(_sc,"arr");
_t[8]=ath_scope_get(_sc,"i");
_t[9]=ath_index(_t[7],_t[8]);
_args[0]=_t[6];
_args[1]=_t[9];
_t[10]=ath_builtin_APPEND(_sc,2,_args);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_args[3]=_t[5];
_args[4]=_t[10];
_t[11]=_rite__array_set_loop(_sc,5,_args);
        _ret=_t[11]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_record_received(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"pkt_num",_argc>0?_argv[0]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"recv_set");
_t[1]=ath_scope_get(_sc,"pkt_num");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_bool(1);
_args[0]=_t[0];
_args[1]=_t[2];
_args[2]=_t[3];
_t[4]=ath_builtin_SET(_sc,3,_args);
        ath_scope_set(_sc,"recv_set",_t[4]);
        }
        {
        _t[0]=ath_scope_get(_sc,"pkt_num");
_t[1]=ath_scope_get(_sc,"recv_largest");
_t[2]=ath_gt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"pkt_num");
            ath_scope_set(_sc,"recv_largest",_t[0]);
            }
        }
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_build_ack_ranges(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"recv_largest");
_t[1]=ath_int(0L);
_t[2]=ath_lt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_array_val(ath_array_new(0));
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_int(0L);
_t[1]=ath_scope_get(_sc,"recv_largest");
_t[2]=ath_array_val(ath_array_new(0));
_t[3]=ath_bool(0);
_t[4]=ath_int(0L);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_args[3]=_t[3];
_args[4]=_t[4];
_t[5]=_rite__build_ranges(_sc,5,_args);
        _ret=_t[5]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite__build_ranges(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"i",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"max_pn",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"ranges",_argc>2?_argv[2]:ath_void(),0);
    ath_scope_define(_sc,"in_run",_argc>3?_argv[3]:ath_void(),0);
    ath_scope_define(_sc,"run_start",_argc>4?_argv[4]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_scope_get(_sc,"max_pn");
_t[2]=ath_gt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"in_run");
            if (ath_is_truthy(_t[0])) {
                {
                _t[0]=ath_scope_get(_sc,"ranges");
_t[1]=ath_array_val(ath_array_new(0));
_t[2]=ath_scope_get(_sc,"run_start");
_args[0]=_t[1];_args[1]=_t[2];
_t[1]=ath_builtin_APPEND(_sc,2,_args);
_t[3]=ath_scope_get(_sc,"max_pn");
_args[0]=_t[1];_args[1]=_t[3];
_t[1]=ath_builtin_APPEND(_sc,2,_args);
_args[0]=_t[0];
_args[1]=_t[1];
_t[4]=ath_builtin_APPEND(_sc,2,_args);
                _ret=_t[4]; goto _done;
                }
            }
            }
            {
            _t[0]=ath_scope_get(_sc,"ranges");
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"recv_set");
_t[1]=ath_scope_get(_sc,"i");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_args[0]=_t[0];
_args[1]=_t[2];
_t[3]=ath_builtin_HAS(_sc,2,_args);
        ath_scope_define(_sc,"have_it",_t[3],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"have_it");
if(ath_is_truthy(_t[0])){_t[1]=ath_scope_get(_sc,"in_run");
_t[2]=ath_bool(!ath_is_truthy(_t[1]));
_t[3]=ath_bool(ath_is_truthy(_t[2]));}else{_t[3]=ath_bool(0);}
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
_t[3]=ath_scope_get(_sc,"max_pn");
_t[4]=ath_scope_get(_sc,"ranges");
_t[5]=ath_bool(1);
_t[6]=ath_scope_get(_sc,"i");
_args[0]=_t[2];
_args[1]=_t[3];
_args[2]=_t[4];
_args[3]=_t[5];
_args[4]=_t[6];
_t[7]=_rite__build_ranges(_sc,5,_args);
            _ret=_t[7]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"have_it");
if(ath_is_truthy(_t[0])){_t[1]=ath_scope_get(_sc,"in_run");
_t[2]=ath_bool(ath_is_truthy(_t[1]));}else{_t[2]=ath_bool(0);}
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
_t[3]=ath_scope_get(_sc,"max_pn");
_t[4]=ath_scope_get(_sc,"ranges");
_t[5]=ath_bool(1);
_t[6]=ath_scope_get(_sc,"run_start");
_args[0]=_t[2];
_args[1]=_t[3];
_args[2]=_t[4];
_args[3]=_t[5];
_args[4]=_t[6];
_t[7]=_rite__build_ranges(_sc,5,_args);
            _ret=_t[7]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"have_it");
_t[1]=ath_bool(!ath_is_truthy(_t[0]));
if(ath_is_truthy(_t[1])){_t[2]=ath_scope_get(_sc,"in_run");
_t[3]=ath_bool(ath_is_truthy(_t[2]));}else{_t[3]=ath_bool(0);}
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_scope_get(_sc,"ranges");
_t[1]=ath_array_val(ath_array_new(0));
_t[2]=ath_scope_get(_sc,"run_start");
_args[0]=_t[1];_args[1]=_t[2];
_t[1]=ath_builtin_APPEND(_sc,2,_args);
_t[3]=ath_scope_get(_sc,"i");
_t[4]=ath_int(1L);
_t[5]=ath_sub(_t[3],_t[4]);
_args[0]=_t[1];_args[1]=_t[5];
_t[1]=ath_builtin_APPEND(_sc,2,_args);
_args[0]=_t[0];
_args[1]=_t[1];
_t[6]=ath_builtin_APPEND(_sc,2,_args);
            ath_scope_define(_sc,"closed",_t[6],0);
            }
            {
            _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
_t[3]=ath_scope_get(_sc,"max_pn");
_t[4]=ath_scope_get(_sc,"closed");
_t[5]=ath_bool(0);
_t[6]=ath_int(0L);
_args[0]=_t[2];
_args[1]=_t[3];
_args[2]=_t[4];
_args[3]=_t[5];
_args[4]=_t[6];
_t[7]=_rite__build_ranges(_sc,5,_args);
            _ret=_t[7]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
_t[3]=ath_scope_get(_sc,"max_pn");
_t[4]=ath_scope_get(_sc,"ranges");
_t[5]=ath_bool(0);
_t[6]=ath_int(0L);
_args[0]=_t[2];
_args[1]=_t[3];
_args[2]=_t[4];
_args[3]=_t[5];
_args[4]=_t[6];
_t[7]=_rite__build_ranges(_sc,5,_args);
        _ret=_t[7]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_count_newly_acked(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"ranges",_argc>0?_argv[0]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"sent_packets");
_args[0]=_t[0];
_t[1]=ath_builtin_KEYS(_sc,1,_args);
        ath_scope_define(_sc,"all_keys",_t[1],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"ranges");
_t[1]=ath_scope_get(_sc,"all_keys");
_t[2]=ath_int(0L);
_t[3]=ath_int(0L);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_args[3]=_t[3];
_t[4]=_rite__count_acked_loop(_sc,4,_args);
        _ret=_t[4]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite__count_acked_loop(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"ranges",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"keys",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"i",_argc>2?_argv[2]:ath_void(),0);
    ath_scope_define(_sc,"acc",_argc>3?_argv[3]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_scope_get(_sc,"keys");
_args[0]=_t[1];
_t[2]=ath_builtin_LENGTH(_sc,1,_args);
_t[3]=ath_ge(_t[0],_t[2]);
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_scope_get(_sc,"acc");
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"keys");
_t[1]=ath_scope_get(_sc,"i");
_t[2]=ath_index(_t[0],_t[1]);
        ath_scope_define(_sc,"key",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"key");
_args[0]=_t[0];
_args[1]=_t[1];
_t[2]=ath_builtin_HAS(_sc,2,_args);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"key");
_t[2]=ath_index(_t[0],_t[1]);
            ath_scope_define(_sc,"pkt",_t[2],0);
            }
            {
            _t[0]=ath_scope_get(_sc,"pkt");
_t[1]=ath_member(_t[0],"pkt_num");
_t[2]=ath_scope_get(_sc,"ranges");
_args[0]=_t[1];
_args[1]=_t[2];
_t[4]=ath_scope_get(_sc,"Pkt");
_t[5]=ath_member(_t[4],"is_acked");
_t[3]=ath_call_sync(_sc,_t[5],2,_args);
            if (ath_is_truthy(_t[3])) {
                {
                _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"key");
_args[0]=_t[0];
_args[1]=_t[1];
_t[2]=ath_builtin_DELETE(_sc,2,_args);
                ath_scope_set(_sc,"sent_packets",_t[2]);
                }
                {
                _t[0]=ath_scope_get(_sc,"ranges");
_t[1]=ath_scope_get(_sc,"keys");
_t[2]=ath_scope_get(_sc,"i");
_t[3]=ath_int(1L);
_t[4]=ath_add(_t[2],_t[3]);
_t[5]=ath_scope_get(_sc,"acc");
_t[6]=ath_scope_get(_sc,"pkt");
_t[7]=ath_member(_t[6],"size");
_t[8]=ath_add(_t[5],_t[7]);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[4];
_args[3]=_t[8];
_t[9]=_rite__count_acked_loop(_sc,4,_args);
                _ret=_t[9]; goto _done;
                }
            }
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"ranges");
_t[1]=ath_scope_get(_sc,"keys");
_t[2]=ath_scope_get(_sc,"i");
_t[3]=ath_int(1L);
_t[4]=ath_add(_t[2],_t[3]);
_t[5]=ath_scope_get(_sc,"acc");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[4];
_args[3]=_t[5];
_t[6]=_rite__count_acked_loop(_sc,4,_args);
        _ret=_t[6]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_detect_losses(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"ack",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"now",_argc>1?_argv[1]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"sent_packets");
_args[0]=_t[0];
_t[1]=ath_builtin_KEYS(_sc,1,_args);
        ath_scope_define(_sc,"all_keys",_t[1],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc_state");
_args[0]=_t[0];
_t[2]=ath_scope_get(_sc,"CC");
_t[3]=ath_member(_t[2],"time_loss_threshold");
_t[1]=ath_call_sync(_sc,_t[3],1,_args);
        ath_scope_define(_sc,"time_thresh",_t[1],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"ack");
_t[1]=ath_scope_get(_sc,"now");
_t[2]=ath_scope_get(_sc,"time_thresh");
_t[3]=ath_scope_get(_sc,"all_keys");
_t[4]=ath_int(0L);
_t[5]=ath_int(0L);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_args[3]=_t[3];
_args[4]=_t[4];
_args[5]=_t[5];
_t[6]=_rite__detect_loss_loop(_sc,6,_args);
        _ret=_t[6]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite__detect_loss_loop(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"ack",_argc>0?_argv[0]:ath_void(),0);
    ath_scope_define(_sc,"now",_argc>1?_argv[1]:ath_void(),0);
    ath_scope_define(_sc,"time_thresh",_argc>2?_argv[2]:ath_void(),0);
    ath_scope_define(_sc,"keys",_argc>3?_argv[3]:ath_void(),0);
    ath_scope_define(_sc,"i",_argc>4?_argv[4]:ath_void(),0);
    ath_scope_define(_sc,"lost_acc",_argc>5?_argv[5]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"i");
_t[1]=ath_scope_get(_sc,"keys");
_args[0]=_t[1];
_t[2]=ath_builtin_LENGTH(_sc,1,_args);
_t[3]=ath_ge(_t[0],_t[2]);
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_scope_get(_sc,"lost_acc");
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"keys");
_t[1]=ath_scope_get(_sc,"i");
_t[2]=ath_index(_t[0],_t[1]);
        ath_scope_define(_sc,"key",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"key");
_args[0]=_t[0];
_args[1]=_t[1];
_t[2]=ath_builtin_HAS(_sc,2,_args);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"key");
_t[2]=ath_index(_t[0],_t[1]);
            ath_scope_define(_sc,"pkt",_t[2],0);
            }
            {
            _t[0]=ath_scope_get(_sc,"pkt");
_t[1]=ath_member(_t[0],"pkt_num");
_t[2]=ath_scope_get(_sc,"ack");
_t[3]=ath_member(_t[2],"largest_acked");
_t[4]=ath_lt(_t[1],_t[3]);
            if (ath_is_truthy(_t[4])) {
                {
                _t[0]=ath_scope_get(_sc,"ack");
_t[1]=ath_member(_t[0],"largest_acked");
_t[2]=ath_scope_get(_sc,"pkt");
_t[3]=ath_member(_t[2],"pkt_num");
_t[4]=ath_sub(_t[1],_t[3]);
                ath_scope_define(_sc,"gap",_t[4],0);
                }
                {
                _t[0]=ath_scope_get(_sc,"gap");
_t[1]=ath_scope_get(_sc,"LOSS_THRESHOLD");
_t[2]=ath_ge(_t[0],_t[1]);
                ath_scope_define(_sc,"pkt_thresh_lost",_t[2],0);
                }
                {
                _t[0]=ath_scope_get(_sc,"now");
_t[1]=ath_scope_get(_sc,"pkt");
_t[2]=ath_member(_t[1],"send_time");
_t[3]=ath_sub(_t[0],_t[2]);
_args[0]=_t[3];
_t[4]=ath_builtin_INT(_sc,1,_args);
                ath_scope_define(_sc,"elapsed",_t[4],0);
                }
                {
                _t[0]=ath_scope_get(_sc,"elapsed");
_t[1]=ath_scope_get(_sc,"time_thresh");
_t[2]=ath_gt(_t[0],_t[1]);
                ath_scope_define(_sc,"time_thresh_lost",_t[2],0);
                }
                {
                _t[0]=ath_scope_get(_sc,"pkt_thresh_lost");
if(ath_is_truthy(_t[0])){_t[2]=ath_bool(1);}else{_t[1]=ath_scope_get(_sc,"time_thresh_lost");
_t[2]=ath_bool(ath_is_truthy(_t[1]));}
                if (ath_is_truthy(_t[2])) {
                    {
                    _t[0]=ath_str_cstr("[LOST] pkt=");
_t[1]=ath_scope_get(_sc,"pkt");
_t[2]=ath_member(_t[1],"pkt_num");
_args[0]=_t[2];
_t[3]=ath_builtin_STRING(_sc,1,_args);
_t[4]=ath_add(_t[0],_t[3]);
_t[5]=ath_str_cstr(" (gap=");
_t[6]=ath_add(_t[4],_t[5]);
_t[7]=ath_scope_get(_sc,"gap");
_args[0]=_t[7];
_t[8]=ath_builtin_STRING(_sc,1,_args);
_t[9]=ath_add(_t[6],_t[8]);
_t[10]=ath_str_cstr(" elapsed=");
_t[11]=ath_add(_t[9],_t[10]);
_t[12]=ath_scope_get(_sc,"elapsed");
_args[0]=_t[12];
_t[13]=ath_builtin_STRING(_sc,1,_args);
_t[14]=ath_add(_t[11],_t[13]);
_t[15]=ath_str_cstr("ms");
_t[16]=ath_add(_t[14],_t[15]);
_t[17]=ath_str_cstr(" thresh=");
_t[18]=ath_add(_t[16],_t[17]);
_t[19]=ath_scope_get(_sc,"time_thresh");
_args[0]=_t[19];
_t[20]=ath_builtin_STRING(_sc,1,_args);
_t[21]=ath_add(_t[18],_t[20]);
_t[22]=ath_str_cstr("ms)");
_t[23]=ath_add(_t[21],_t[22]);
_args[0]=_t[23];
_t[24]=ath_builtin_UTTER(_sc,1,_args);
                    (void)_t[24];
                    }
                    {
                    _t[0]=ath_scope_get(_sc,"pkt");
_t[1]=ath_member(_t[0],"size");
_t[2]=ath_int(0L);
_t[3]=ath_gt(_t[1],_t[2]);
                    if (ath_is_truthy(_t[3])) {
                        {
                        _t[0]=ath_scope_get(_sc,"retransmit_queue");
_t[1]=ath_scope_get(_sc,"pkt");
_args[0]=_t[0];
_args[1]=_t[1];
_t[2]=ath_builtin_APPEND(_sc,2,_args);
                        ath_scope_set(_sc,"retransmit_queue",_t[2]);
                        }
                    }
                    }
                    {
                    _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"key");
_args[0]=_t[0];
_args[1]=_t[1];
_t[2]=ath_builtin_DELETE(_sc,2,_args);
                    ath_scope_set(_sc,"sent_packets",_t[2]);
                    }
                    {
                    _t[0]=ath_scope_get(_sc,"ack");
_t[1]=ath_scope_get(_sc,"now");
_t[2]=ath_scope_get(_sc,"time_thresh");
_t[3]=ath_scope_get(_sc,"keys");
_t[4]=ath_scope_get(_sc,"i");
_t[5]=ath_int(1L);
_t[6]=ath_add(_t[4],_t[5]);
_t[7]=ath_scope_get(_sc,"lost_acc");
_t[8]=ath_scope_get(_sc,"pkt");
_t[9]=ath_member(_t[8],"size");
_t[10]=ath_add(_t[7],_t[9]);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_args[3]=_t[3];
_args[4]=_t[6];
_args[5]=_t[10];
_t[11]=_rite__detect_loss_loop(_sc,6,_args);
                    _ret=_t[11]; goto _done;
                    }
                }
                }
            }
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"ack");
_t[1]=ath_scope_get(_sc,"now");
_t[2]=ath_scope_get(_sc,"time_thresh");
_t[3]=ath_scope_get(_sc,"keys");
_t[4]=ath_scope_get(_sc,"i");
_t[5]=ath_int(1L);
_t[6]=ath_add(_t[4],_t[5]);
_t[7]=ath_scope_get(_sc,"lost_acc");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_args[3]=_t[3];
_args[4]=_t[6];
_args[5]=_t[7];
_t[8]=_rite__detect_loss_loop(_sc,6,_args);
        _ret=_t[8]; goto _done;
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_process_ack(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"ack",_argc>0?_argv[0]:ath_void(),0);
    _ret = ath_void();
        {
        _t[0]=ath_builtin_TIME(_sc,0,_args);
        ath_scope_define(_sc,"now",_t[0],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"now");
        ath_scope_set(_sc,"last_ack_time",_t[0]);
        }
        {
        _t[0]=ath_int(0L);
        ath_scope_set(_sc,"pto_count",_t[0]);
        }
        {
        _t[0]=ath_str_cstr("[ACK] largest=");
_t[1]=ath_scope_get(_sc,"ack");
_t[2]=ath_member(_t[1],"largest_acked");
_args[0]=_t[2];
_t[3]=ath_builtin_STRING(_sc,1,_args);
_t[4]=ath_add(_t[0],_t[3]);
_t[5]=ath_str_cstr(" ranges=");
_t[6]=ath_add(_t[4],_t[5]);
_t[7]=ath_scope_get(_sc,"ack");
_t[8]=ath_member(_t[7],"ack_ranges");
_args[0]=_t[8];
_t[9]=ath_builtin_STRING(_sc,1,_args);
_t[10]=ath_add(_t[6],_t[9]);
_t[11]=ath_str_cstr(" cwnd=");
_t[12]=ath_add(_t[10],_t[11]);
_t[13]=ath_scope_get(_sc,"cc_state");
_t[14]=ath_member(_t[13],"cwnd");
_args[0]=_t[14];
_t[15]=ath_builtin_STRING(_sc,1,_args);
_t[16]=ath_add(_t[12],_t[15]);
_t[17]=ath_str_cstr(" inflight=");
_t[18]=ath_add(_t[16],_t[17]);
_t[19]=ath_scope_get(_sc,"cc_state");
_t[20]=ath_member(_t[19],"bytes_in_flight");
_args[0]=_t[20];
_t[21]=ath_builtin_STRING(_sc,1,_args);
_t[22]=ath_add(_t[18],_t[21]);
_args[0]=_t[22];
_t[23]=ath_builtin_UTTER(_sc,1,_args);
        (void)_t[23];
        }
        {
        _t[0]=ath_scope_get(_sc,"ack");
_t[1]=ath_member(_t[0],"largest_acked");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
        ath_scope_define(_sc,"acked_pkt_key",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"acked_pkt_key");
_args[0]=_t[0];
_args[1]=_t[1];
_t[2]=ath_builtin_HAS(_sc,2,_args);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"acked_pkt_key");
_t[2]=ath_index(_t[0],_t[1]);
            ath_scope_define(_sc,"orig",_t[2],0);
            }
            {
            _t[0]=ath_scope_get(_sc,"now");
_t[1]=ath_scope_get(_sc,"orig");
_t[2]=ath_member(_t[1],"send_time");
_t[3]=ath_sub(_t[0],_t[2]);
_args[0]=_t[3];
_t[4]=ath_builtin_INT(_sc,1,_args);
            ath_scope_define(_sc,"latest_rtt",_t[4],0);
            }
            {
            _t[0]=ath_scope_get(_sc,"latest_rtt");
_t[1]=ath_int(0L);
_t[2]=ath_gt(_t[0],_t[1]);
            if (ath_is_truthy(_t[2])) {
                {
                _t[0]=ath_scope_get(_sc,"cc_state");
_t[1]=ath_scope_get(_sc,"latest_rtt");
_t[2]=ath_scope_get(_sc,"ack");
_t[3]=ath_member(_t[2],"ack_delay");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[3];
_t[5]=ath_scope_get(_sc,"CC");
_t[6]=ath_member(_t[5],"update_rtt");
_t[4]=ath_call_sync(_sc,_t[6],3,_args);
                ath_scope_set(_sc,"cc_state",_t[4]);
                }
            }
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"ack");
_t[1]=ath_member(_t[0],"ack_ranges");
_args[0]=_t[1];
_t[2]=_rite_count_newly_acked(_sc,1,_args);
        ath_scope_define(_sc,"acked_bytes",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"acked_bytes");
_t[1]=ath_int(0L);
_t[2]=ath_gt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"cc_state");
_t[1]=ath_scope_get(_sc,"acked_bytes");
_t[2]=ath_scope_get(_sc,"now");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[4]=ath_scope_get(_sc,"CC");
_t[5]=ath_member(_t[4],"on_ack");
_t[3]=ath_call_sync(_sc,_t[5],3,_args);
            ath_scope_set(_sc,"cc_state",_t[3]);
            }
            {
            _t[0]=ath_scope_get(_sc,"total_acked");
_t[1]=ath_scope_get(_sc,"acked_bytes");
_t[2]=ath_add(_t[0],_t[1]);
            ath_scope_set(_sc,"total_acked",_t[2]);
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"ack");
_t[1]=ath_scope_get(_sc,"now");
_args[0]=_t[0];
_args[1]=_t[1];
_t[2]=_rite_detect_losses(_sc,2,_args);
        ath_scope_define(_sc,"lost_bytes",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"lost_bytes");
_t[1]=ath_int(0L);
_t[2]=ath_gt(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_scope_get(_sc,"cc_state");
_t[1]=ath_scope_get(_sc,"lost_bytes");
_t[2]=ath_scope_get(_sc,"now");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[4]=ath_scope_get(_sc,"CC");
_t[5]=ath_member(_t[4],"on_loss");
_t[3]=ath_call_sync(_sc,_t[5],3,_args);
            ath_scope_set(_sc,"cc_state",_t[3]);
            }
            {
            _t[0]=ath_str_cstr("[LOSS] lost_bytes=");
_t[1]=ath_scope_get(_sc,"lost_bytes");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_add(_t[0],_t[2]);
_t[4]=ath_str_cstr(" new_cwnd=");
_t[5]=ath_add(_t[3],_t[4]);
_t[6]=ath_scope_get(_sc,"cc_state");
_t[7]=ath_member(_t[6],"cwnd");
_args[0]=_t[7];
_t[8]=ath_builtin_STRING(_sc,1,_args);
_t[9]=ath_add(_t[5],_t[8]);
_t[10]=ath_str_cstr(" ssthresh=");
_t[11]=ath_add(_t[9],_t[10]);
_t[12]=ath_scope_get(_sc,"cc_state");
_t[13]=ath_member(_t[12],"ssthresh");
_args[0]=_t[13];
_t[14]=ath_builtin_STRING(_sc,1,_args);
_t[15]=ath_add(_t[11],_t[14]);
_args[0]=_t[15];
_t[16]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[16];
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"csv_log");
_t[1]=ath_scope_get(_sc,"now");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_add(_t[0],_t[2]);
_t[4]=ath_str_cstr(",");
_t[5]=ath_add(_t[3],_t[4]);
_t[6]=ath_scope_get(_sc,"cc_state");
_t[7]=ath_member(_t[6],"cwnd");
_args[0]=_t[7];
_t[8]=ath_builtin_STRING(_sc,1,_args);
_t[9]=ath_add(_t[5],_t[8]);
_t[10]=ath_str_cstr(",");
_t[11]=ath_add(_t[9],_t[10]);
_t[12]=ath_scope_get(_sc,"cc_state");
_t[13]=ath_member(_t[12],"bytes_in_flight");
_args[0]=_t[13];
_t[14]=ath_builtin_STRING(_sc,1,_args);
_t[15]=ath_add(_t[11],_t[14]);
_t[16]=ath_str_cstr(",");
_t[17]=ath_add(_t[15],_t[16]);
_t[18]=ath_scope_get(_sc,"cc_state");
_t[19]=ath_member(_t[18],"smoothed_rtt");
_args[0]=_t[19];
_t[20]=ath_builtin_STRING(_sc,1,_args);
_t[21]=ath_add(_t[17],_t[20]);
_t[22]=ath_str_cstr(",");
_t[23]=ath_add(_t[21],_t[22]);
_t[24]=ath_scope_get(_sc,"total_lost");
_args[0]=_t[24];
_t[25]=ath_builtin_STRING(_sc,1,_args);
_t[26]=ath_add(_t[23],_t[25]);
_t[27]=ath_str_cstr("\n");
_t[28]=ath_add(_t[26],_t[27]);
        ath_scope_set(_sc,"csv_log",_t[28]);
        }
        {
        _t[0]=ath_scope_get(_sc,"total_acked");
_t[1]=ath_scope_get(_sc,"TARGET_BYTES");
_t[2]=ath_ge(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_bool(1);
            ath_scope_set(_sc,"simulation_done",_t[0]);
            }
        }
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_transmit_packet(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    ath_scope_define(_sc,"pkt",_argc>0?_argv[0]:ath_void(),0);
    _ret = ath_void();
        {
        _t[1]=ath_scope_get(_sc,"Net");
_t[2]=ath_member(_t[1],"is_lost");
_t[0]=ath_call_sync(_sc,_t[2],0,_args);
_t[3]=ath_bool(!ath_is_truthy(_t[0]));
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_str_cstr("[RX] pkt=");
_t[1]=ath_scope_get(_sc,"pkt");
_t[2]=ath_member(_t[1],"pkt_num");
_args[0]=_t[2];
_t[3]=ath_builtin_STRING(_sc,1,_args);
_t[4]=ath_add(_t[0],_t[3]);
_t[5]=ath_str_cstr(" stream=");
_t[6]=ath_add(_t[4],_t[5]);
_t[7]=ath_scope_get(_sc,"pkt");
_t[8]=ath_member(_t[7],"stream_id");
_args[0]=_t[8];
_t[9]=ath_builtin_STRING(_sc,1,_args);
_t[10]=ath_add(_t[6],_t[9]);
_args[0]=_t[10];
_t[11]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[11];
            }
            {
            _t[0]=ath_scope_get(_sc,"pkt");
_t[1]=ath_member(_t[0],"pkt_num");
_args[0]=_t[1];
_t[2]=_rite_record_received(_sc,1,_args);
            (void)_t[2];
            }
            {
            _t[0]=ath_bool(1);
            ath_scope_set(_sc,"needs_ack",_t[0]);
            }
        } else {
            {
            _t[0]=ath_scope_get(_sc,"total_lost");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
            ath_scope_set(_sc,"total_lost",_t[2]);
            }
            {
            _t[0]=ath_str_cstr("[NET] LOST pkt=");
_t[1]=ath_scope_get(_sc,"pkt");
_t[2]=ath_member(_t[1],"pkt_num");
_args[0]=_t[2];
_t[3]=ath_builtin_STRING(_sc,1,_args);
_t[4]=ath_add(_t[0],_t[3]);
_args[0]=_t[4];
_t[5]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[5];
            }
        }
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_drain_retransmit_queue(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"retransmit_queue");
_args[0]=_t[0];
_t[1]=ath_builtin_LENGTH(_sc,1,_args);
_t[2]=ath_int(0L);
_t[3]=ath_eq(_t[1],_t[2]);
        if (ath_is_truthy(_t[3])) {
            {
            _t[0]=ath_void();
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"cc_state");
_t[1]=ath_scope_get(_sc,"CHUNK_SIZE");
_args[0]=_t[0];
_args[1]=_t[1];
_t[3]=ath_scope_get(_sc,"CC");
_t[4]=ath_member(_t[3],"can_send");
_t[2]=ath_call_sync(_sc,_t[4],2,_args);
_t[5]=ath_bool(!ath_is_truthy(_t[2]));
        if (ath_is_truthy(_t[5])) {
            {
            _t[0]=ath_void();
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"retransmit_queue");
_args[0]=_t[0];
_t[1]=ath_builtin_FIRST(_sc,1,_args);
        ath_scope_define(_sc,"old_pkt",_t[1],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"retransmit_queue");
_t[1]=ath_int(1L);
_t[2]=ath_scope_get(_sc,"retransmit_queue");
_args[0]=_t[2];
_t[3]=ath_builtin_LENGTH(_sc,1,_args);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[3];
_t[4]=ath_builtin_SLICE(_sc,3,_args);
        ath_scope_set(_sc,"retransmit_queue",_t[4]);
        }
        {
        _t[0]=ath_builtin_TIME(_sc,0,_args);
        ath_scope_define(_sc,"now",_t[0],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"old_pkt");
_t[1]=ath_scope_get(_sc,"next_pkt_num");
_t[2]=ath_scope_get(_sc,"now");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[4]=ath_scope_get(_sc,"Pkt");
_t[5]=ath_member(_t[4],"make_retransmit");
_t[3]=ath_call_sync(_sc,_t[5],3,_args);
        ath_scope_define(_sc,"pkt",_t[3],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"next_pkt_num");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_scope_get(_sc,"pkt");
_args[0]=_t[0];
_args[1]=_t[2];
_args[2]=_t[3];
_t[4]=ath_builtin_SET(_sc,3,_args);
        ath_scope_set(_sc,"sent_packets",_t[4]);
        }
        {
        _t[0]=ath_scope_get(_sc,"next_pkt_num");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
        ath_scope_set(_sc,"next_pkt_num",_t[2]);
        }
        {
        _t[0]=ath_scope_get(_sc,"total_retransmits");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
        ath_scope_set(_sc,"total_retransmits",_t[2]);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc_state");
_t[1]=ath_str_cstr("bytes_in_flight");
_t[2]=ath_scope_get(_sc,"cc_state");
_t[3]=ath_member(_t[2],"bytes_in_flight");
_t[4]=ath_scope_get(_sc,"pkt");
_t[5]=ath_member(_t[4],"size");
_t[6]=ath_add(_t[3],_t[5]);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[6];
_t[7]=ath_builtin_SET(_sc,3,_args);
        ath_scope_set(_sc,"cc_state",_t[7]);
        }
        {
        _t[0]=ath_str_cstr("[RTX] pkt=");
_t[1]=ath_scope_get(_sc,"pkt");
_t[2]=ath_member(_t[1],"pkt_num");
_args[0]=_t[2];
_t[3]=ath_builtin_STRING(_sc,1,_args);
_t[4]=ath_add(_t[0],_t[3]);
_t[5]=ath_str_cstr(" (was pkt=");
_t[6]=ath_add(_t[4],_t[5]);
_t[7]=ath_scope_get(_sc,"pkt");
_t[8]=ath_member(_t[7],"original_pkt_num");
_args[0]=_t[8];
_t[9]=ath_builtin_STRING(_sc,1,_args);
_t[10]=ath_add(_t[6],_t[9]);
_t[11]=ath_str_cstr(")");
_t[12]=ath_add(_t[10],_t[11]);
_t[13]=ath_str_cstr(" stream=");
_t[14]=ath_add(_t[12],_t[13]);
_t[15]=ath_scope_get(_sc,"pkt");
_t[16]=ath_member(_t[15],"stream_id");
_args[0]=_t[16];
_t[17]=ath_builtin_STRING(_sc,1,_args);
_t[18]=ath_add(_t[14],_t[17]);
_t[19]=ath_str_cstr(" offset=");
_t[20]=ath_add(_t[18],_t[19]);
_t[21]=ath_scope_get(_sc,"pkt");
_t[22]=ath_member(_t[21],"offset");
_args[0]=_t[22];
_t[23]=ath_builtin_STRING(_sc,1,_args);
_t[24]=ath_add(_t[20],_t[23]);
_args[0]=_t[24];
_t[25]=ath_builtin_UTTER(_sc,1,_args);
        (void)_t[25];
        }
        {
        _t[0]=ath_scope_get(_sc,"pkt");
_args[0]=_t[0];
_t[1]=_rite_transmit_packet(_sc,1,_args);
        (void)_t[1];
        }
        {
        _t[0]=_rite_drain_retransmit_queue(_sc,0,_args);
        (void)_t[0];
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_send_burst(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"total_sent");
_t[1]=ath_scope_get(_sc,"TARGET_BYTES");
_t[2]=ath_ge(_t[0],_t[1]);
        if (ath_is_truthy(_t[2])) {
            {
            _t[0]=ath_void();
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"cc_state");
_t[1]=ath_scope_get(_sc,"CHUNK_SIZE");
_args[0]=_t[0];
_args[1]=_t[1];
_t[3]=ath_scope_get(_sc,"CC");
_t[4]=ath_member(_t[3],"can_send");
_t[2]=ath_call_sync(_sc,_t[4],2,_args);
_t[5]=ath_bool(!ath_is_truthy(_t[2]));
        if (ath_is_truthy(_t[5])) {
            {
            _t[0]=ath_void();
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=ath_scope_get(_sc,"stream_state");
_t[1]=ath_scope_get(_sc,"last_stream");
_args[0]=_t[0];
_args[1]=_t[1];
_t[3]=ath_scope_get(_sc,"Streams");
_t[4]=ath_member(_t[3],"pick_stream");
_t[2]=ath_call_sync(_sc,_t[4],2,_args);
        ath_scope_set(_sc,"last_stream",_t[2]);
        }
        {
        _t[0]=ath_scope_get(_sc,"stream_state");
_t[1]=ath_scope_get(_sc,"last_stream");
_t[2]=ath_index(_t[0],_t[1]);
        ath_scope_define(_sc,"stream",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"stream");
_t[1]=ath_scope_get(_sc,"CHUNK_SIZE");
_args[0]=_t[0];
_args[1]=_t[1];
_t[3]=ath_scope_get(_sc,"Streams");
_t[4]=ath_member(_t[3],"next_chunk");
_t[2]=ath_call_sync(_sc,_t[4],2,_args);
        ath_scope_define(_sc,"chunk",_t[2],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"stream");
_t[1]=ath_str_cstr("send_offset");
_t[2]=ath_scope_get(_sc,"chunk");
_t[3]=ath_member(_t[2],"new_offset");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[3];
_t[4]=ath_builtin_SET(_sc,3,_args);
        ath_scope_define(_sc,"updated_stream",_t[4],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"stream_state");
_t[1]=ath_scope_get(_sc,"last_stream");
_t[2]=ath_scope_get(_sc,"updated_stream");
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[2];
_t[3]=_rite_array_set(_sc,3,_args);
        ath_scope_set(_sc,"stream_state",_t[3]);
        }
        {
        _t[0]=ath_builtin_TIME(_sc,0,_args);
        ath_scope_define(_sc,"now",_t[0],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"next_pkt_num");
_t[1]=ath_scope_get(_sc,"chunk");
_t[2]=ath_member(_t[1],"stream_id");
_t[3]=ath_scope_get(_sc,"chunk");
_t[4]=ath_member(_t[3],"offset");
_t[5]=ath_scope_get(_sc,"chunk");
_t[6]=ath_member(_t[5],"size");
_t[7]=ath_scope_get(_sc,"now");
_args[0]=_t[0];
_args[1]=_t[2];
_args[2]=_t[4];
_args[3]=_t[6];
_args[4]=_t[7];
_t[9]=ath_scope_get(_sc,"Pkt");
_t[10]=ath_member(_t[9],"make_packet");
_t[8]=ath_call_sync(_sc,_t[10],5,_args);
        ath_scope_define(_sc,"pkt",_t[8],0);
        }
        {
        _t[0]=ath_scope_get(_sc,"sent_packets");
_t[1]=ath_scope_get(_sc,"next_pkt_num");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_scope_get(_sc,"pkt");
_args[0]=_t[0];
_args[1]=_t[2];
_args[2]=_t[3];
_t[4]=ath_builtin_SET(_sc,3,_args);
        ath_scope_set(_sc,"sent_packets",_t[4]);
        }
        {
        _t[0]=ath_scope_get(_sc,"next_pkt_num");
_t[1]=ath_int(1L);
_t[2]=ath_add(_t[0],_t[1]);
        ath_scope_set(_sc,"next_pkt_num",_t[2]);
        }
        {
        _t[0]=ath_scope_get(_sc,"total_sent");
_t[1]=ath_scope_get(_sc,"CHUNK_SIZE");
_t[2]=ath_add(_t[0],_t[1]);
        ath_scope_set(_sc,"total_sent",_t[2]);
        }
        {
        _t[0]=ath_scope_get(_sc,"cc_state");
_t[1]=ath_str_cstr("bytes_in_flight");
_t[2]=ath_scope_get(_sc,"cc_state");
_t[3]=ath_member(_t[2],"bytes_in_flight");
_t[4]=ath_scope_get(_sc,"CHUNK_SIZE");
_t[5]=ath_add(_t[3],_t[4]);
_args[0]=_t[0];
_args[1]=_t[1];
_args[2]=_t[5];
_t[6]=ath_builtin_SET(_sc,3,_args);
        ath_scope_set(_sc,"cc_state",_t[6]);
        }
        {
        _t[0]=ath_str_cstr("[TX] pkt=");
_t[1]=ath_scope_get(_sc,"pkt");
_t[2]=ath_member(_t[1],"pkt_num");
_args[0]=_t[2];
_t[3]=ath_builtin_STRING(_sc,1,_args);
_t[4]=ath_add(_t[0],_t[3]);
_t[5]=ath_str_cstr(" stream=");
_t[6]=ath_add(_t[4],_t[5]);
_t[7]=ath_scope_get(_sc,"pkt");
_t[8]=ath_member(_t[7],"stream_id");
_args[0]=_t[8];
_t[9]=ath_builtin_STRING(_sc,1,_args);
_t[10]=ath_add(_t[6],_t[9]);
_t[11]=ath_str_cstr(" cwnd=");
_t[12]=ath_add(_t[10],_t[11]);
_t[13]=ath_scope_get(_sc,"cc_state");
_t[14]=ath_member(_t[13],"cwnd");
_args[0]=_t[14];
_t[15]=ath_builtin_STRING(_sc,1,_args);
_t[16]=ath_add(_t[12],_t[15]);
_t[17]=ath_str_cstr(" inflight=");
_t[18]=ath_add(_t[16],_t[17]);
_t[19]=ath_scope_get(_sc,"cc_state");
_t[20]=ath_member(_t[19],"bytes_in_flight");
_args[0]=_t[20];
_t[21]=ath_builtin_STRING(_sc,1,_args);
_t[22]=ath_add(_t[18],_t[21]);
_args[0]=_t[22];
_t[23]=ath_builtin_UTTER(_sc,1,_args);
        (void)_t[23];
        }
        {
        _t[0]=ath_scope_get(_sc,"pkt");
_args[0]=_t[0];
_t[1]=_rite_transmit_packet(_sc,1,_args);
        (void)_t[1];
        }
        {
        _t[0]=_rite_send_burst(_sc,0,_args);
        (void)_t[0];
        }
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

static AthValue _rite_sim_cycle(AthScope *_closure,int _argc,AthValue *_argv) {
    AthScope *_sc;
    AthValue _t[128]; AthValue _args[16]; AthValue _ret;
    (void)_argc;
    _sc = ath_scope_new(_closure);
    memset(_t,0,sizeof(_t));
    _ret = ath_void();
        {
        _t[0]=ath_scope_get(_sc,"simulation_done");
        if (ath_is_truthy(_t[0])) {
            {
            _t[0]=ath_str_cstr("");
_args[0]=_t[0];
_t[1]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[1];
            }
            {
            _t[0]=ath_str_cstr("=== Simulation Complete ===");
_args[0]=_t[0];
_t[1]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[1];
            }
            {
            _t[0]=ath_str_cstr("Total sent:         ");
_t[1]=ath_scope_get(_sc,"total_sent");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_add(_t[0],_t[2]);
_args[0]=_t[3];
_t[4]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[4];
            }
            {
            _t[0]=ath_str_cstr("Total acked:        ");
_t[1]=ath_scope_get(_sc,"total_acked");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_add(_t[0],_t[2]);
_args[0]=_t[3];
_t[4]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[4];
            }
            {
            _t[0]=ath_str_cstr("Total lost:         ");
_t[1]=ath_scope_get(_sc,"total_lost");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_add(_t[0],_t[2]);
_args[0]=_t[3];
_t[4]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[4];
            }
            {
            _t[0]=ath_str_cstr("Total retransmits:  ");
_t[1]=ath_scope_get(_sc,"total_retransmits");
_args[0]=_t[1];
_t[2]=ath_builtin_STRING(_sc,1,_args);
_t[3]=ath_add(_t[0],_t[2]);
_args[0]=_t[3];
_t[4]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[4];
            }
            {
            _t[0]=ath_str_cstr("Final cwnd:         ");
_t[1]=ath_scope_get(_sc,"cc_state");
_t[2]=ath_member(_t[1],"cwnd");
_args[0]=_t[2];
_t[3]=ath_builtin_STRING(_sc,1,_args);
_t[4]=ath_add(_t[0],_t[3]);
_args[0]=_t[4];
_t[5]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[5];
            }
            {
            _t[0]=ath_str_cstr("Final SRTT:         ");
_t[1]=ath_scope_get(_sc,"cc_state");
_t[2]=ath_member(_t[1],"smoothed_rtt");
_args[0]=_t[2];
_t[3]=ath_builtin_STRING(_sc,1,_args);
_t[4]=ath_add(_t[0],_t[3]);
_t[5]=ath_str_cstr("ms");
_t[6]=ath_add(_t[4],_t[5]);
_args[0]=_t[6];
_t[7]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[7];
            }
            {
            _t[0]=ath_str_cstr("./cwnd_log.csv");
_t[1]=ath_scope_get(_sc,"csv_log");
_args[0]=_t[0];
_args[1]=_t[1];
_t[2]=ath_builtin_INSCRIBE(_sc,2,_args);
            (void)_t[2];
            }
            {
            _t[0]=ath_str_cstr("Wrote cwnd_log.csv");
_args[0]=_t[0];
_t[1]=ath_builtin_UTTER(_sc,1,_args);
            (void)_t[1];
            }
            {
            _t[0]=ath_void();
            _ret=_t[0]; goto _done;
            }
        }
        }
        {
        _t[0]=_rite_drain_retransmit_queue(_sc,0,_args);
        (void)_t[0];
        }
        {
        _t[0]=_rite_send_burst(_sc,0,_args);
        (void)_t[0];
        }
        { AthEntity *_e=ath_entity_timer_new("rtt_wait",100UL);
          ath_scope_define(_sc,"rtt_wait",ath_entity_val(_e),0); }
        /* ~ATH in sync ctx - unsupported */
    _done:
    ath_scope_decref(_sc);
    return _ret;
}

struct _FMain { AthCont base; AthScope *scope; };
static _FMain* _FMain_new(AthCont *next,AthScope *par) {
    _FMain *f=(_FMain*)malloc(sizeof(_FMain));
    f->base.resume=_s0__FMain; f->base.next=next; f->base.refcount=1;
    f->scope=ath_scope_new(par); return f; }
static void _FMain_free(_FMain *f){ath_scope_decref(f->scope);free(f);}
static void _s0__FMain(AthCont *_self,AthValue _result) {
    _FMain *f=(_FMain*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    f->base.resume=_s3__FMain;
    { _FMod1 *_mf=_FMod1_new((AthCont*)f,f->scope);
      ath_eventloop_schedule((AthCont*)_mf,ath_void()); }
    return;
}
static void _s3__FMain(AthCont *_self, AthValue _result) {
    _FMain *f=(_FMain*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    f->base.resume=_s6__FMain;
    { _FMod4 *_mf=_FMod4_new((AthCont*)f,f->scope);
      ath_eventloop_schedule((AthCont*)_mf,ath_void()); }
    return;
}
static void _s6__FMain(AthCont *_self, AthValue _result) {
    _FMain *f=(_FMain*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    f->base.resume=_s9__FMain;
    { _FMod7 *_mf=_FMod7_new((AthCont*)f,f->scope);
      ath_eventloop_schedule((AthCont*)_mf,ath_void()); }
    return;
}
static void _s9__FMain(AthCont *_self, AthValue _result) {
    _FMain *f=(_FMain*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    f->base.resume=_s12__FMain;
    { _FMod10 *_mf=_FMod10_new((AthCont*)f,f->scope);
      ath_eventloop_schedule((AthCont*)_mf,ath_void()); }
    return;
}
static void _s12__FMain(AthCont *_self, AthValue _result) {
    _FMain *f=(_FMain*)_self;
    AthValue _t[128]; AthValue _args[16];
    (void)_result; memset(_t,0,sizeof(_t));
    {
    _t[1]=ath_scope_get(f->scope,"CC");
_t[2]=ath_member(_t[1],"init_cc");
_t[0]=ath_call_sync(f->scope,_t[2],0,_args);
    ath_scope_define(f->scope,"cc_state",_t[0],0);
    }

    {
    _t[3]=ath_int(0L);
    ath_scope_define(f->scope,"next_pkt_num",_t[3],0);
    }

    {
    _t[4]=ath_map_val(ath_map_new(0));
    ath_scope_define(f->scope,"sent_packets",_t[4],0);
    }

    {
    _t[5]=ath_int(4L);
_args[0]=_t[5];
_t[7]=ath_scope_get(f->scope,"Streams");
_t[8]=ath_member(_t[7],"init_streams");
_t[6]=ath_call_sync(f->scope,_t[8],1,_args);
    ath_scope_define(f->scope,"stream_state",_t[6],0);
    }

    {
    _t[9]=ath_int(0L);
    ath_scope_define(f->scope,"last_stream",_t[9],0);
    }

    {
    _t[10]=ath_int(0L);
    ath_scope_define(f->scope,"total_sent",_t[10],0);
    }

    {
    _t[11]=ath_int(0L);
    ath_scope_define(f->scope,"total_acked",_t[11],0);
    }

    {
    _t[12]=ath_int(0L);
    ath_scope_define(f->scope,"total_lost",_t[12],0);
    }

    {
    _t[13]=ath_int(0L);
    ath_scope_define(f->scope,"total_retransmits",_t[13],0);
    }

    {
    _t[14]=ath_bool(0);
    ath_scope_define(f->scope,"simulation_done",_t[14],0);
    }

    {
    _t[15]=ath_array_val(ath_array_new(0));
    ath_scope_define(f->scope,"retransmit_queue",_t[15],0);
    }

    {
    _t[16]=ath_int(0L);
    ath_scope_define(f->scope,"pto_count",_t[16],0);
    }

    {
    _t[17]=ath_int(0L);
    ath_scope_define(f->scope,"last_ack_time",_t[17],0);
    }

    {
    _t[18]=ath_int(0L);
_t[19]=ath_int(1L);
_t[20]=ath_sub(_t[18],_t[19]);
    ath_scope_define(f->scope,"recv_largest",_t[20],0);
    }

    {
    _t[21]=ath_map_val(ath_map_new(0));
    ath_scope_define(f->scope,"recv_set",_t[21],0);
    }

    {
    _t[22]=ath_str_cstr("timestamp_ms,cwnd,bytes_in_flight,srtt_ms,total_lost\n");
    ath_scope_define(f->scope,"csv_log",_t[22],0);
    }

    {
    _t[23]=ath_bool(0);
    ath_scope_define(f->scope,"needs_ack",_t[23],0);
    }

    {
    _t[24]=ath_int(50000L);
    ath_scope_define(f->scope,"TARGET_BYTES",_t[24],1);
    }

    {
    _t[25]=ath_int(1200L);
    ath_scope_define(f->scope,"CHUNK_SIZE",_t[25],1);
    }

    {
    _t[26]=ath_int(25L);
    ath_scope_define(f->scope,"MAX_ACK_DELAY",_t[26],1);
    }

    {
    _t[27]=ath_int(3L);
    ath_scope_define(f->scope,"LOSS_THRESHOLD",_t[27],1);
    }

    {
    _t[28]=ath_str_cstr("=== QUIC Transport Simulation ===");
_args[0]=_t[28];
_t[29]=ath_builtin_UTTER(f->scope,1,_args);
    (void)_t[29];
    }

    {
    _t[30]=ath_str_cstr("Streams: 4 | Target: ");
_t[31]=ath_scope_get(f->scope,"TARGET_BYTES");
_args[0]=_t[31];
_t[32]=ath_builtin_STRING(f->scope,1,_args);
_t[33]=ath_add(_t[30],_t[32]);
_t[34]=ath_str_cstr(" bytes");
_t[35]=ath_add(_t[33],_t[34]);
_args[0]=_t[35];
_t[36]=ath_builtin_UTTER(f->scope,1,_args);
    (void)_t[36];
    }

    {
    _t[37]=ath_str_cstr("Link: ");
_t[38]=ath_scope_get(f->scope,"Net");
_t[39]=ath_member(_t[38],"BASE_RTT");
_args[0]=_t[39];
_t[40]=ath_builtin_STRING(f->scope,1,_args);
_t[41]=ath_add(_t[37],_t[40]);
_t[42]=ath_str_cstr("ms base RTT, ");
_t[43]=ath_add(_t[41],_t[42]);
_t[44]=ath_scope_get(f->scope,"Net");
_t[45]=ath_member(_t[44],"LOSS_RATE");
_t[46]=ath_float(100.0);
_t[47]=ath_mul(_t[45],_t[46]);
_args[0]=_t[47];
_t[48]=ath_builtin_STRING(f->scope,1,_args);
_t[49]=ath_add(_t[43],_t[48]);
_t[50]=ath_str_cstr("% loss");
_t[51]=ath_add(_t[49],_t[50]);
_args[0]=_t[51];
_t[52]=ath_builtin_UTTER(f->scope,1,_args);
    (void)_t[52];
    }

    {
    _t[53]=ath_str_cstr("");
_args[0]=_t[53];
_t[54]=ath_builtin_UTTER(f->scope,1,_args);
    (void)_t[54];
    }

    ath_scope_define(f->scope,"array_set",ath_rite_val(ath_rite_new_sync(f->scope,_rite_array_set,3)),0);

    ath_scope_define(f->scope,"_array_set_loop",ath_rite_val(ath_rite_new_sync(f->scope,_rite__array_set_loop,5)),0);

    ath_scope_define(f->scope,"record_received",ath_rite_val(ath_rite_new_sync(f->scope,_rite_record_received,1)),0);

    ath_scope_define(f->scope,"build_ack_ranges",ath_rite_val(ath_rite_new_sync(f->scope,_rite_build_ack_ranges,0)),0);

    ath_scope_define(f->scope,"_build_ranges",ath_rite_val(ath_rite_new_sync(f->scope,_rite__build_ranges,5)),0);

    ath_scope_define(f->scope,"count_newly_acked",ath_rite_val(ath_rite_new_sync(f->scope,_rite_count_newly_acked,1)),0);

    ath_scope_define(f->scope,"_count_acked_loop",ath_rite_val(ath_rite_new_sync(f->scope,_rite__count_acked_loop,4)),0);

    ath_scope_define(f->scope,"detect_losses",ath_rite_val(ath_rite_new_sync(f->scope,_rite_detect_losses,2)),0);

    ath_scope_define(f->scope,"_detect_loss_loop",ath_rite_val(ath_rite_new_sync(f->scope,_rite__detect_loss_loop,6)),0);

    ath_scope_define(f->scope,"process_ack",ath_rite_val(ath_rite_new_sync(f->scope,_rite_process_ack,1)),0);

    ath_scope_define(f->scope,"transmit_packet",ath_rite_val(ath_rite_new_sync(f->scope,_rite_transmit_packet,1)),0);

    ath_scope_define(f->scope,"drain_retransmit_queue",ath_rite_val(ath_rite_new_sync(f->scope,_rite_drain_retransmit_queue,0)),0);

    ath_scope_define(f->scope,"send_burst",ath_rite_val(ath_rite_new_sync(f->scope,_rite_send_burst,0)),0);

    ath_scope_define(f->scope,"sim_cycle",ath_rite_val(ath_rite_new_sync(f->scope,_rite_sim_cycle,0)),0);

    {
    _t[55]=_rite_sim_cycle(f->scope,0,_args);
    (void)_t[55];
    }

    ath_entity_die(ath_scope_get(f->scope,"THIS").as.entity);

    _FMain_free(f);
}
int main(void) {
    AthScope  *global;
    AthEntity *_this;
    _FMain    *_frame;
    ath_eventloop_init();
    global = ath_scope_new(NULL);
    ath_scope_define_builtins(global);
    _this = ath_entity_this_new();
    ath_scope_define(global,"THIS",ath_entity_val(_this),0);
    ath_scope_define(global,"sim_cycle",ath_rite_val(ath_rite_new_sync(global,_rite_sim_cycle,-1)),0);
    ath_scope_define(global,"build_ack_ranges",ath_rite_val(ath_rite_new_sync(global,_rite_build_ack_ranges,-1)),0);
    ath_scope_define(global,"_array_set_loop",ath_rite_val(ath_rite_new_sync(global,_rite__array_set_loop,-1)),0);
    ath_scope_define(global,"record_received",ath_rite_val(ath_rite_new_sync(global,_rite_record_received,-1)),0);
    ath_scope_define(global,"transmit_packet",ath_rite_val(ath_rite_new_sync(global,_rite_transmit_packet,-1)),0);
    ath_scope_define(global,"array_set",ath_rite_val(ath_rite_new_sync(global,_rite_array_set,-1)),0);
    ath_scope_define(global,"process_ack",ath_rite_val(ath_rite_new_sync(global,_rite_process_ack,-1)),0);
    ath_scope_define(global,"count_newly_acked",ath_rite_val(ath_rite_new_sync(global,_rite_count_newly_acked,-1)),0);
    ath_scope_define(global,"_build_ranges",ath_rite_val(ath_rite_new_sync(global,_rite__build_ranges,-1)),0);
    ath_scope_define(global,"_detect_loss_loop",ath_rite_val(ath_rite_new_sync(global,_rite__detect_loss_loop,-1)),0);
    ath_scope_define(global,"detect_losses",ath_rite_val(ath_rite_new_sync(global,_rite_detect_losses,-1)),0);
    ath_scope_define(global,"_count_acked_loop",ath_rite_val(ath_rite_new_sync(global,_rite__count_acked_loop,-1)),0);
    ath_scope_define(global,"send_burst",ath_rite_val(ath_rite_new_sync(global,_rite_send_burst,-1)),0);
    ath_scope_define(global,"drain_retransmit_queue",ath_rite_val(ath_rite_new_sync(global,_rite_drain_retransmit_queue,-1)),0);
    _frame = _FMain_new(NULL,global);
    ath_eventloop_schedule((AthCont*)_frame,ath_void());
    ath_eventloop_run();
    ath_scope_decref(global);
    return 0;
}

